[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
# background = "#161821"
background = "#000000"
foreground = "#d2d4de"

[font]
size = 16.0
normal.family = "Monaco"
bold.family = "Monaco"
italic.family = "Monaco"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
# columns = 0
decorations = "none"
# lines = 0
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
    {key = "Minus", mods = "Command|Shift", action = "IncreaseFontSize" },
    {key = ";", mods = "Command|Shift", action = "IncreaseFontSize" },
    {key = "Semicolon", mods = "Command|Shift", action = "IncreaseFontSize" },
    {key = "Semicolon", mods = "Super|Shift", action = "IncreaseFontSize" },
    {key = "Semicolon", mods = "Command", action = "IncreaseFontSize" },
    {key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    {key = "^", mods = "Command", action = "IncreaseFontSize" },
    {key = "¥", chars = "\\" },
]
