window:
  columns: 0
  lines: 0

  # position:
  #   x: 0
  #   y: 0

  padding:
    x: 0
    y: 0

  decorations: none

  # Startup Mode (changes require restart)
  #
  # Values for `startup_mode`:
  #   - Windowed
  #   - Maximized
  #   - Fullscreen
  #
  # Values for `startup_mode` (macOS only):
  #   - SimpleFullscreen
  #startup_mode: Windowed

font:
  normal:
    family: Cica
    style: Regular
  bold:
    family: Cica
    style: Bold
  italic:
    family: Cica
    style: Italic
  bold_italic:
    family: Cica
    style: Bold Italic

  size: 16.0

  offset:
    x: 0 
    y: 0

  glyph_offset:
    x: 0
    y: 0

# Colors (Iceberg Dark)
colors:
  # Default colors
  primary:
    background: '#161821'
    foreground: '#d2d4de'

  # Normal colors
  normal:
    black:   '#161821'
    red:     '#e27878'
    green:   '#b4be82'
    yellow:  '#e2a478'
    blue:    '#84a0c6'
    magenta: '#a093c7'
    cyan:    '#89b8c2'
    white:   '#c6c8d1'

  # Bright colors
  bright:
    black:   '#6b7089'
    red:     '#e98989'
    green:   '#c0ca8e'
    yellow:  '#e9b189'
    blue:    '#91acd1'
    magenta: '#ada0d3'
    cyan:    '#95c4ce'
    white:   '#d2d4de'

key_bindings:
  - { key: Add,      mods: Control|Shift,       action: IncreaseFontSize }

