#!/usr/bin/env sh
export LANG="ja_JP.UTF-8"
export LC_CTYPE="ja_JP.UTF-8"
export XMODIFIERS="@im=fcitx"
export XMODIFIER="@im=fcitx"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export DefaultIMModule=fcitx

if type "setxkbmap" > /dev/null 2>&1; then
  # capsキーをctrlキーに
  setxkbmap -option ctrl:nocaps
fi
if type "gsettings" > /dev/null 2>&1; then
  # capsキーをctrlキーに
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
fi
if type "xset" > /dev/null 2>&1; then
  # 200msで30Hzのキーリピート
  xset r rate 200 30
fi
