#!/usr/bin/env sh
export LANG="ja_JP.UTF-8"
export LC_CTYPE="ja_JP.UTF-8"
export XMODIFIERS="@im=fcitx"
export XMODIFIER="@im=fcitx"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export DefaultIMModule=fcitx

