name: 'Check, scripts'
on:
  push:
    branches:
      - master

jobs:
  check_scripts:
    name: Check scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Shellcheck
        run: sudo apt-get install shellcheck
      - name: Run Shellcheck
        run: make check
        shell: bash
      - name: Run Installation Script
        run: './install.sh overwrite'
        shell: bash
      - name: Run Installation Script Twice
        run: |
          ./install.sh overwrite
          ./install.sh overwrite
        shell: bash
