name: 'Check, scripts'
on:
  push:
    branch:
      - master

jobs:
  check_scripts:
    name: Check scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC1071
      - name: Run Installation Script
        run: python3 install.py
        shell: bash
