name: 'Check, scripts'
on:
  push:
    branch:
      - master

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2034
        with:
          ignore:
            - zshrc
            - zshenv

