name: 'Check, scripts'
on:
  push:
    branch:
      - master

jobs:
  check_scripts:
    name: Check scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Shellcheck
        run: sudo apt-get install shellcheck
      - name: Run Shellcheck
        run: make check
        shell: bash
      - name: Run Installation Script
        run: python3 install.py
        shell: bash
      - name: Run Installation Script Twice
        run: |
          python3 install.py
          python3 install.py
        shell: bash
